# Generated by Django 4.1.3 on 2022-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('NONE', 'NONE'), ('IN', 'IN'), ('OUT', 'OUT'), ('IN_OUT', 'IN & OUT')], default='NONE', max_length=10)),
            ],
        ),
    ]
