# Generated by Django 4.1.3 on 2022-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gate',
            options={'verbose_name': 'Gate configuration', 'verbose_name_plural': 'Gate configurations'},
        ),
        migrations.AddField(
            model_name='gate',
            name='relay_open_barrier_pin',
            field=models.IntegerField(db_column='relay_open_barrier_pin', default=0, verbose_name='Barrier open trigger relay'),
        ),
        migrations.AddField(
            model_name='gate',
            name='sensor_barrier_open_pin',
            field=models.IntegerField(db_column='sensor_barrier_open_pin', default=0, verbose_name='Sensor for barrier opening'),
        ),
        migrations.AddField(
            model_name='gate',
            name='sensor_barrier_override_pin',
            field=models.IntegerField(db_column='sensor_barrier_override_pin', default=0, verbose_name='Sensor for barrier open'),
        ),
        migrations.AddField(
            model_name='gate',
            name='sensor_presence_detector_pin',
            field=models.IntegerField(db_column='sensor_presence_detector_pin', default=0, verbose_name='Presence detector pin'),
        ),
    ]
