# Generated by Django 4.1.3 on 2022-11-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_gate_options_gate_relay_open_barrier_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='sensor_barrier_override_pin',
        ),
        migrations.AlterField(
            model_name='gate',
            name='relay_open_barrier_pin',
            field=models.IntegerField(db_column='relay_open_barrier_pin', default=0, help_text='Pin number of the relay that triggers the opening of the boom under normal operation', verbose_name='Barrier open trigger relay pin'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='sensor_barrier_open_pin',
            field=models.IntegerField(db_column='sensor_barrier_open_pin', default=0, help_text='Pin number of sensor (e.g. push button) that indicates that the boom needs to be opened', verbose_name='Sensor pin for barrier opening'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='sensor_presence_detector_pin',
            field=models.IntegerField(db_column='sensor_presence_detector_pin', default=0, help_text='Pin number of the sensor (e.g. push button) that indicates presence of an object at the gate e.g. vehicle', verbose_name='Presence detector pin'),
        ),
    ]
