# Generated by Django 4.1.3 on 2022-11-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_product_alter_movement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(choices=[('PER_HOUR', 'Per Hour'), ('PER_DAY', 'Per Day'), ('FLAT_FEE', 'Flat Fee')], default='PER_HOUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reference_number',
            field=models.CharField(default='11adce65-648c-457a-aea9-7914c8894d7d', editable=False, max_length=50, unique=True, verbose_name='Barcode'),
        ),
    ]
